#!/usr/bin/env python3
"""Scan the EAGLE3 training corpora for overlap with the eval benchmarks.

Why this matters for a *speculator* specifically: the draft is trained to predict
the target's next tokens, and the training corpus's assistant turns were
regenerated by the same target the eval scores acceptance against, with eval
running greedy (``temperature: 0.0``). An eval prompt present in training means
the draft memorized exactly the continuation being measured, which inflates
``accept_rate``/``accept_length`` directly. Task accuracy is not the metric at
risk here; acceptance is.

Four detectors, cheapest/strictest first (see ``contamination_lib`` for the
template-stripping step every one of them depends on):

  exact      normalized token-stream hash                 -- zero false positives
  ngram13    fraction of the eval item's 13-grams found    -- GPT-3/Llama standard
  run        longest verbatim token run found              -- the readable number
  minhash    est. Jaccard vs the nearest training doc      -- catches restatements

The eval side is tiny (~3.5k prompts), so the index is built there and the
corpora are streamed once, in parallel, checking every training n-gram against
it. Memory stays flat regardless of corpus size.

Assistant turns are scanned too (``ngram13_resp``): an eval problem quoted inside
a training *response* is a weaker leak than a prompt match, but still means the
draft trained on target tokens for that problem.

Usage:
    python detect_contamination.py                       # all corpora, all benchmarks
    python detect_contamination.py --workers 64
    python detect_contamination.py --limit-rows 20000    # smoke test
    python detect_contamination.py --sources kimi,nemotron_math

Outputs (into --output-dir, default ./out):
    contamination_report.json   per-benchmark summary + thresholds
    contamination_report.md     the human-readable version
    eval_item_scores.jsonl      every eval item with all four scores
    review_pairs.jsonl          flagged items + matching training text, for tier-4
                                manual adjudication
"""

from __future__ import annotations

import argparse
import collections
import json
import multiprocessing as mp
import os
import sys
import time
from dataclasses import dataclass
from pathlib import Path

import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parent))
from contamination_lib import (  # noqa: E402
    MinHasher,
    eval_core,
    exact_key,
    longest_run,
    ngram_hashes,
    tokens,
    train_core,
)

REPO = Path(__file__).resolve().parents[3]
EVAL_DATA_DIR = REPO / "scripts/evaluate/mtp_server_eval/data"
RESULTS_DIR = REPO / "scripts/evaluate/experiments/results"

# Training corpora, keyed by the split that introduced them. The merged
# train_regen_*.jsonl files under datasets/ are dedup'd unions of exactly these,
# so scanning the sources covers every corpus while keeping per-split
# attribution (a merged file's UUID row ids cannot tell stem from code).
DEFAULT_SOURCES = {
    "kimi": "/sms-scratch/ravira/datasets/train_regen.jsonl",
    "nemotron_stem": str(REPO / "output/nemotron_v2/nemotron-v2__stem_regen_gemma-4-31B-it_.jsonl"),
    "nemotron_code": str(REPO / "output/nemotron_v2/nemotron-v2__code_regen_gemma-4-31B-it_.jsonl"),
    "nemotron_math": str(REPO / "output/nemotron_v2/nemotron-v2__math_regen_gemma-4-31B-it_.jsonl"),
}

# Which splits each trained draft saw -> which experiments a hit invalidates.
CORPUS_COMPOSITION = {
    "gemma4_draft_model_300k_eagle3": ["kimi"],
    "gemma4_draft_model_300k_eagle3_kimi_mtp_stem": ["kimi", "nemotron_stem"],
    "gemma4_draft_model_300k_eagle3_kimi_mtp_stem_code": [
        "kimi",
        "nemotron_stem",
        "nemotron_code",
    ],
    "gemma4_draft_model_900k_eagle3_kimi_mtp_stem_code_math": [
        "kimi",
        "nemotron_stem",
        "nemotron_code",
        "nemotron_math",
    ],
}

N_LONG = 13  # primary n-gram order (GPT-3 / Llama convention)
N_SHORT = 8  # fallback for eval items too short to yield 13-grams

# Flag thresholds. These select *candidates for review*, they are not verdicts;
# tier 4 (review_pairs.jsonl) is where a candidate becomes a finding.
THRESHOLDS = {
    "run_dirty": 25,       # >=25 verbatim tokens in a row is not coincidence
    "run_suspect": N_LONG, # any 13-gram hit at all
    "ngram13_dirty": 0.20, # Llama-style 20% containment
    # A rephrased copy breaks long runs: aime/61 is present verbatim in
    # nemotron_math but written \(ABC\) instead of $ABC$ with the point renamed
    # D -> P, which caps 13-gram containment at 0.26. The shorter order survives
    # that kind of edit, so it carries the recall for paraphrased math items.
    "ngram8_dirty": 0.50,
    "minhash_dirty": 0.70,
    "minhash_suspect": 0.50,
}

# Per-document bar for keeping a training excerpt as reviewable evidence. Set
# well below the dirty bar: an item can clear `dirty` on containment pooled over
# several documents while no single document is itself striking, and a flagged
# item with no evidence attached cannot be adjudicated at tier 4.
EVIDENCE_MIN_13GRAMS = 4

# Containment is a ratio, so it is meaningless when the denominator is tiny: a
# 9-token mbpp prompt has just two 8-gram positions, and matching one of them on
# generic phrasing ("write a python function to ...") yields c8 = 0.50 by pure
# chance. Require this many n-gram positions before a containment ratio may flag
# an item. Below it, only exact match / long verbatim run / MinHash can flag --
# which for a 10-token prompt is exactly the right standard.
MIN_NGRAM_POSITIONS = 10

# An n-gram occurring in this many DISTINCT eval items is template phrasing, not
# problem content -- e.g. AIME's "...where m and n are relatively prime positive
# integers. Find m+n." or LiveCodeBench's "The first line contains a single
# integer t, the number of test cases". Such n-grams match training text
# constantly and produce long spurious runs (aime/65's entire 40-token "run" was
# the AIME answer-format sentence, with none of its actual problem in training).
# They are excluded from both the hit sets and the containment denominators, so
# every score below is computed over problem-specific content only.
BOILERPLATE_MIN_ITEMS = 5

CHUNK_BYTES = 64 << 20

# Populated in the parent before fork; workers inherit copy-on-write.
_IDX: "EvalIndex | None" = None


# --------------------------------------------------------------------------
# Eval-side index
# --------------------------------------------------------------------------


def _drop_numeric(toks: list[str], hashes: list[int], n: int) -> list[int | None]:
    """Blank out n-grams whose tokens are all numeric, keeping positions aligned."""
    return [
        None if all(t.isdigit() for t in toks[i : i + n]) else h
        for i, h in enumerate(hashes)
    ]


@dataclass
class EvalItem:
    benchmark: str
    item_id: str
    prompt: str
    core: str
    n_tokens: int
    n_long: int   # number of 13-gram positions
    n_short: int  # number of 8-gram positions


class EvalIndex:
    """Inverted index over the eval prompts: the small side of the comparison."""

    def __init__(self, items: list[EvalItem], hasher: MinHasher):
        self.items = items
        self.hasher = hasher
        self.exact: dict[int, list[int]] = collections.defaultdict(list)
        self.long: dict[int, list[tuple[int, int]]] = collections.defaultdict(list)
        self.short: dict[int, list[tuple[int, int]]] = collections.defaultdict(list)
        self.buckets: dict[int, list[int]] = collections.defaultdict(list)
        self.signatures: list[np.ndarray | None] = []

        # First pass: hash every item, and count in how many distinct items each
        # n-gram occurs so template phrasing can be identified and dropped.
        per_item: list[tuple[list[int], list[int]]] = []
        df_long: collections.Counter = collections.Counter()
        df_short: collections.Counter = collections.Counter()
        for item in items:
            toks = tokens(item.core)
            # All-numeric n-grams carry no linguistic content: sample grids and
            # I/O tables collide across unrelated problems. livecodebench/abc327_c
            # ("verify a 9x9 grid") shared 424 13-grams with an unrelated Aizu
            # Sudoku *solver* purely through digit rows, at MinHash Jaccard 0.0.
            # A genuinely duplicated problem always shares prose too, so dropping
            # these removes the false-positive class without masking real hits.
            longs = _drop_numeric(toks, ngram_hashes(toks, N_LONG), N_LONG)
            shorts = _drop_numeric(toks, ngram_hashes(toks, N_SHORT), N_SHORT)
            per_item.append((longs, shorts))
            df_long.update({h for h in longs if h is not None})
            df_short.update({h for h in shorts if h is not None})

        self.boilerplate_long = {h for h, c in df_long.items() if c >= BOILERPLATE_MIN_ITEMS}
        self.boilerplate_short = {h for h, c in df_short.items() if c >= BOILERPLATE_MIN_ITEMS}

        for idx, item in enumerate(items):
            toks = tokens(item.core)
            longs, shorts = per_item[idx]
            self.exact[exact_key(item.core)].append(idx)
            # Keep the position numbering of the FULL token stream so that
            # consecutive-position runs still mean "contiguous in the original
            # text"; only the boilerplate positions are omitted.
            n_long_eff = n_short_eff = 0
            for pos, h in enumerate(longs):
                if h is None or h in self.boilerplate_long:
                    continue
                self.long[h].append((idx, pos))
                n_long_eff += 1
            for pos, h in enumerate(shorts):
                if h is None or h in self.boilerplate_short:
                    continue
                self.short[h].append((idx, pos))
                n_short_eff += 1
            # Denominators over problem-specific content only.
            item.n_long = n_long_eff
            item.n_short = n_short_eff

            signature = hasher.signature(hasher.shingles(toks))
            self.signatures.append(signature)
            if signature is not None:
                for key in hasher.band_keys(signature):
                    self.buckets[key].append(idx)

        # Plain dicts pickle/fork more cheaply and avoid accidental key growth.
        self.exact = dict(self.exact)
        self.long = dict(self.long)
        self.short = dict(self.short)
        self.buckets = dict(self.buckets)


def load_eval_items(data_dir: Path, benchmarks: set[str] | None) -> list[EvalItem]:
    items: list[EvalItem] = []
    for path in sorted(data_dir.glob("*.jsonl")):
        name = path.stem
        if benchmarks and name not in benchmarks:
            continue
        with path.open() as handle:
            for line_no, line in enumerate(handle):
                line = line.strip()
                if not line:
                    continue
                row = json.loads(line)
                prompt = row.get("prompt") or ""
                if not prompt:
                    continue
                core = eval_core(prompt)
                toks = tokens(core)
                items.append(
                    EvalItem(
                        benchmark=row.get("benchmark", name),
                        item_id=str(row.get("id", line_no)),
                        prompt=prompt,
                        core=core,
                        n_tokens=len(toks),
                        n_long=max(0, len(toks) - N_LONG + 1),
                        n_short=max(0, len(toks) - N_SHORT + 1),
                    )
                )
    return items


# --------------------------------------------------------------------------
# Corpus scan
# --------------------------------------------------------------------------


def _turns(row: dict) -> list[tuple[str, str]]:
    """Yield (role, text) with `from`/`value` and `role`/`content` both handled."""
    convo = row.get("conversations") or row.get("messages") or []
    out = []
    for turn in convo:
        if not isinstance(turn, dict):
            continue
        role = turn.get("from") or turn.get("role") or ""
        text = turn.get("value") or turn.get("content") or ""
        if isinstance(text, str) and text:
            out.append((role.lower(), text))
    return out


def _iter_chunk(path: str, start: int, end: int):
    """Yield rows whose starting byte falls in [start, end), respecting lines."""
    with open(path, "rb") as handle:
        if start:
            handle.seek(start - 1)
            handle.readline()  # discard the partial line owned by the prior chunk
        else:
            handle.seek(0)
        while handle.tell() < end:
            raw = handle.readline()
            if not raw:
                return
            raw = raw.strip()
            if not raw:
                continue
            try:
                yield json.loads(raw)
            except json.JSONDecodeError:
                continue


def _scan_chunk(task: tuple[str, str, int, int, int, int]) -> dict:
    """Worker: match one byte-range of one corpus file against the eval index."""
    split, path, start, end, limit_rows, evidence_cap = task
    idx = _IDX
    assert idx is not None
    hasher = idx.hasher

    hits_long: set[tuple[int, int]] = set()
    hits_short: set[tuple[int, int]] = set()
    hits_resp: set[tuple[int, int]] = set()
    exact_hits: dict[int, list[str]] = collections.defaultdict(list)
    best_jaccard: dict[int, float] = {}
    evidence: dict[int, list[dict]] = collections.defaultdict(list)
    rows = 0

    for row in _iter_chunk(path, start, end):
        rows += 1
        if limit_rows and rows > limit_rows:
            break

        turns = _turns(row)
        prompt_text = "\n".join(t for role, t in turns if role in ("human", "user"))
        resp_text = "\n".join(
            t for role, t in turns if role in ("gpt", "assistant", "model")
        )
        if not prompt_text:
            continue

        doc_id = str(row.get("id", ""))
        core = train_core(prompt_text)
        toks = tokens(core)

        # --- tier 1: exact -------------------------------------------------
        matched = idx.exact.get(exact_key(core))
        if matched:
            for item_idx in matched:
                exact_hits[item_idx].append(doc_id)

        # --- tier 2: n-gram containment (prompt side) ----------------------
        per_doc: dict[int, int] = collections.Counter()
        for h in ngram_hashes(toks, N_LONG):
            for pair in idx.long.get(h, ()):
                hits_long.add(pair)
                per_doc[pair[0]] += 1
        for h in ngram_hashes(toks, N_SHORT):
            for pair in idx.short.get(h, ()):
                hits_short.add(pair)

        # --- tier 3: MinHash near-duplicate --------------------------------
        signature = hasher.signature(hasher.shingles(toks))
        doc_jaccard: dict[int, float] = {}
        if signature is not None:
            candidates = set()
            for key in hasher.band_keys(signature):
                candidates.update(idx.buckets.get(key, ()))
            for item_idx in candidates:
                other = idx.signatures[item_idx]
                if other is None:
                    continue
                est = hasher.estimate_jaccard(signature, other)
                doc_jaccard[item_idx] = est
                if est > best_jaccard.get(item_idx, 0.0):
                    best_jaccard[item_idx] = est

        # --- tier 4 material: keep the text behind strong signals ----------
        interesting = set(exact_hits) & {i for i in exact_hits if doc_id in exact_hits[i]}
        interesting |= {i for i, c in per_doc.items() if c >= EVIDENCE_MIN_13GRAMS}
        interesting |= {
            i for i, j in doc_jaccard.items() if j >= THRESHOLDS["minhash_suspect"]
        }
        for item_idx in interesting:
            if len(evidence[item_idx]) < evidence_cap:
                evidence[item_idx].append(
                    {
                        "split": split,
                        "train_id": doc_id,
                        "shared_13grams": per_doc.get(item_idx, 0),
                        "minhash_jaccard": round(doc_jaccard.get(item_idx, 0.0), 3),
                        "exact": doc_id in exact_hits.get(item_idx, []),
                        "train_prompt": prompt_text[:3000],
                        "train_response_head": resp_text[:600],
                    }
                )

        # --- response side (weaker signal, prompt-order n-grams only) ------
        if resp_text:
            for h in ngram_hashes(tokens(train_core(resp_text)), N_LONG):
                for pair in idx.long.get(h, ()):
                    hits_resp.add(pair)

    return {
        "split": split,
        "rows": rows,
        "hits_long": hits_long,
        "hits_short": hits_short,
        "hits_resp": hits_resp,
        "exact_hits": {k: v for k, v in exact_hits.items()},
        "best_jaccard": best_jaccard,
        "evidence": {k: v for k, v in evidence.items()},
    }


def build_tasks(sources: dict[str, str], limit_rows: int, evidence_cap: int) -> list[tuple]:
    tasks = []
    for split, path in sources.items():
        size = os.path.getsize(path)
        for start in range(0, size, CHUNK_BYTES):
            tasks.append(
                (split, path, start, min(start + CHUNK_BYTES, size), limit_rows, evidence_cap)
            )
    return tasks


# --------------------------------------------------------------------------
# Aggregation / reporting
# --------------------------------------------------------------------------


def longest_common_span(a_tokens: list[str], b_tokens: list[str], cap: int = 4000) -> str:
    """Longest run of tokens shared by both texts -- the thing a human should read.

    Reading this one string is usually enough to adjudicate: a shared *problem*
    reads as problem content, while a false positive reads as template phrasing
    ("...where m and n are relatively prime positive integers. Find m+n.").
    """
    a, b = a_tokens[:cap], b_tokens[:cap]
    if not a or not b:
        return ""
    best_len = best_end = 0
    prev = [0] * (len(b) + 1)
    for i in range(1, len(a) + 1):
        cur = [0] * (len(b) + 1)
        ai = a[i - 1]
        for j in range(1, len(b) + 1):
            if ai == b[j - 1]:
                cur[j] = prev[j - 1] + 1
                if cur[j] > best_len:
                    best_len, best_end = cur[j], i
        prev = cur
    return " ".join(a[best_end - best_len : best_end])


def _evaluated_ids() -> dict[str, set[str]]:
    """Which eval ids the experiments actually scored (num_samples caps the set).

    Contamination on an item that was never sampled cannot have moved a headline
    number, so the report separates "in the benchmark file" from "actually used".
    """
    used: dict[str, set[str]] = collections.defaultdict(set)
    for path in RESULTS_DIR.rglob("mtp_eval_details.jsonl"):
        with path.open() as handle:
            for line in handle:
                line = line.strip()
                if not line:
                    continue
                try:
                    row = json.loads(line)
                except json.JSONDecodeError:
                    continue
                if "benchmark" in row and "id" in row:
                    used[row["benchmark"]].add(str(row["id"]))
    return dict(used)


# Verdict policy.
#   "graded"     -- exact match, long verbatim run, containment, or MinHash.
#   "exact-only" -- ONLY a normalized-exact prompt match counts as contamination.
#                   Near-duplicates (a reformatted or reworded copy of the same
#                   problem) are reported in the score columns but treated as
#                   clean. Note "exact" here means exact after tier-0 template
#                   stripping and whitespace/case/punctuation folding; a
#                   byte-exact rule would be vacuous, since the eval harness
#                   wraps every problem in scaffolding no training row carries.
POLICY = "graded"


def classify(score: dict) -> str:
    if POLICY == "exact-only":
        return "dirty" if score["exact_match"] else "clean"
    return _classify_graded(score)


def _classify_graded(score: dict) -> str:
    if score["exact_match"]:
        return "dirty"
    if score["longest_run_tokens"] >= THRESHOLDS["run_dirty"]:
        return "dirty"
    if (
        score.get("n_long_positions", 0) >= MIN_NGRAM_POSITIONS
        and score["ngram13_containment"] >= THRESHOLDS["ngram13_dirty"]
    ):
        return "dirty"
    if (
        score.get("n_short_positions", 0) >= MIN_NGRAM_POSITIONS
        and score.get("ngram8_containment", 0.0) >= THRESHOLDS["ngram8_dirty"]
    ):
        return "dirty"
    if score["minhash_jaccard"] >= THRESHOLDS["minhash_dirty"]:
        return "dirty"
    if (
        score["longest_run_tokens"] >= THRESHOLDS["run_suspect"]
        or score["minhash_jaccard"] >= THRESHOLDS["minhash_suspect"]
    ):
        return "suspect"
    return "clean"


def aggregate(index: EvalIndex, partials: list[dict]) -> tuple[list[dict], dict]:
    per_split_long: dict[str, set] = collections.defaultdict(set)
    per_split_short: dict[str, set] = collections.defaultdict(set)
    hits_long: set = set()
    hits_short: set = set()
    hits_resp: set = set()
    exact: dict[int, dict[str, list[str]]] = collections.defaultdict(
        lambda: collections.defaultdict(list)
    )
    best_j: dict[int, float] = {}
    best_j_split: dict[int, dict[str, float]] = collections.defaultdict(dict)
    evidence: dict[int, list[dict]] = collections.defaultdict(list)
    rows_per_split: dict[str, int] = collections.Counter()

    for part in partials:
        split = part["split"]
        rows_per_split[split] += part["rows"]
        hits_long |= part["hits_long"]
        hits_short |= part["hits_short"]
        hits_resp |= part["hits_resp"]
        per_split_long[split] |= part["hits_long"]
        per_split_short[split] |= part["hits_short"]
        for item_idx, ids in part["exact_hits"].items():
            exact[item_idx][split].extend(ids)
        for item_idx, est in part["best_jaccard"].items():
            best_j[item_idx] = max(best_j.get(item_idx, 0.0), est)
            prev = best_j_split[item_idx].get(split, 0.0)
            best_j_split[item_idx][split] = max(prev, est)
        for item_idx, records in part["evidence"].items():
            evidence[item_idx].extend(records)

    pos_long: dict[int, set[int]] = collections.defaultdict(set)
    for item_idx, pos in hits_long:
        pos_long[item_idx].add(pos)
    pos_short: dict[int, set[int]] = collections.defaultdict(set)
    for item_idx, pos in hits_short:
        pos_short[item_idx].add(pos)
    pos_resp: dict[int, set[int]] = collections.defaultdict(set)
    for item_idx, pos in hits_resp:
        pos_resp[item_idx].add(pos)
    split_pos: dict[str, dict[int, set[int]]] = {
        split: collections.defaultdict(set) for split in per_split_long
    }
    for split, pairs in per_split_long.items():
        for item_idx, pos in pairs:
            split_pos[split][item_idx].add(pos)
    split_pos_short: dict[str, dict[int, set[int]]] = {
        split: collections.defaultdict(set) for split in per_split_short
    }
    for split, pairs in per_split_short.items():
        for item_idx, pos in pairs:
            split_pos_short[split][item_idx].add(pos)

    scores = []
    for idx, item in enumerate(index.items):
        run = longest_run(pos_long.get(idx, set()))
        score = {
            "benchmark": item.benchmark,
            "id": item.item_id,
            "core_tokens": item.n_tokens,
            # Containment denominators; classify() uses them to refuse to flag on
            # a ratio computed over too few positions.
            "n_long_positions": item.n_long,
            "n_short_positions": item.n_short,
            "exact_match": bool(exact.get(idx)),
            "ngram13_containment": round(
                len(pos_long.get(idx, ())) / item.n_long, 4
            ) if item.n_long else 0.0,
            "ngram8_containment": round(
                len(pos_short.get(idx, ())) / item.n_short, 4
            ) if item.n_short else 0.0,
            # run of R consecutive matching 13-grams == R+12 verbatim tokens
            "longest_run_tokens": run + N_LONG - 1 if run else 0,
            "minhash_jaccard": round(best_j.get(idx, 0.0), 3),
            "resp_ngram13_containment": round(
                len(pos_resp.get(idx, ())) / item.n_long, 4
            ) if item.n_long else 0.0,
            # strongest evidence first, so review_pairs.jsonl leads with the
            # match that actually drove the verdict
            "evidence_sorted": sorted(
                evidence.get(idx, []),
                key=lambda e: (e["exact"], e["shared_13grams"], e["minhash_jaccard"]),
                reverse=True,
            ),
            # Any split with at least one 13-gram hit. Shared boilerplate makes
            # this over-inclusive, so it is NOT what attribution should key on.
            "splits_any_hit": sorted(
                {s for s in split_pos if idx in split_pos[s]}
                | set(exact.get(idx, {}))
                | {s for s, j in best_j_split.get(idx, {}).items() if j >= THRESHOLDS["minhash_suspect"]}
            ),
        }
        score["evidence"] = score.pop("evidence_sorted")[:5]
        score["verdict"] = classify(score)
        # Keep the graded assessment as a diagnostic even under exact-only, so
        # the near-duplicate evidence stays inspectable and the policy can be
        # revisited without re-scanning.
        score["graded_verdict"] = (
            score["verdict"] if POLICY == "graded" else _classify_graded(score)
        )

        # Attribution: a split owns this item only if that split *on its own*
        # clears the dirty bar. Without this, one shared boilerplate 13-gram
        # would implicate every corpus and every experiment.
        dirty_splits = []
        for split in score["splits_any_hit"]:
            positions = split_pos.get(split, {}).get(idx, set())
            short_positions = split_pos_short.get(split, {}).get(idx, set())
            run = longest_run(positions)
            sub = {
                "n_long_positions": item.n_long,
                "n_short_positions": item.n_short,
                "exact_match": bool(exact.get(idx, {}).get(split)),
                "longest_run_tokens": run + N_LONG - 1 if run else 0,
                "ngram13_containment": (len(positions) / item.n_long) if item.n_long else 0.0,
                "ngram8_containment": (
                    (len(short_positions) / item.n_short) if item.n_short else 0.0
                ),
                "minhash_jaccard": best_j_split.get(idx, {}).get(split, 0.0),
            }
            if classify(sub) == "dirty":
                dirty_splits.append(split)
        score["splits"] = dirty_splits
        scores.append(score)

    meta = {
        "rows_scanned": dict(rows_per_split),
        "policy": POLICY,
        "thresholds": THRESHOLDS,
        "n_long": N_LONG,
        "n_short": N_SHORT,
    }
    return scores, meta


def summarize(scores: list[dict], used: dict[str, set[str]]) -> list[dict]:
    by_bench: dict[str, list[dict]] = collections.defaultdict(list)
    for score in scores:
        by_bench[score["benchmark"]].append(score)

    rows = []
    for bench, group in sorted(by_bench.items()):
        used_ids = used.get(bench, set())
        scored = [s for s in group if s["id"] in used_ids] if used_ids else []
        rows.append(
            {
                "benchmark": bench,
                "n_items": len(group),
                "dirty": sum(s["verdict"] == "dirty" for s in group),
                "suspect": sum(s["verdict"] == "suspect" for s in group),
                "exact": sum(s["exact_match"] for s in group),
                "max_run_tokens": max((s["longest_run_tokens"] for s in group), default=0),
                "max_ngram13": max((s["ngram13_containment"] for s in group), default=0.0),
                "max_minhash": max((s["minhash_jaccard"] for s in group), default=0.0),
                "n_evaluated": len(scored),
                "evaluated_dirty": sum(s["verdict"] == "dirty" for s in scored),
                "evaluated_suspect": sum(s["verdict"] == "suspect" for s in scored),
                # Graded diagnostics, reported even when the policy is exact-only.
                "graded_dirty": sum(s["graded_verdict"] == "dirty" for s in group),
                "graded_suspect": sum(s["graded_verdict"] == "suspect" for s in group),
                "evaluated_graded_dirty": sum(
                    s["graded_verdict"] == "dirty" for s in scored
                ),
            }
        )
    return rows


def write_markdown(path: Path, summary: list[dict], meta: dict, scores: list[dict]) -> None:
    affected = collections.defaultdict(set)
    for score in scores:
        if score["verdict"] == "dirty":
            for corpus, splits in CORPUS_COMPOSITION.items():
                if set(score["splits"]) & set(splits):
                    affected[corpus].add(f"{score['benchmark']}/{score['id']}")

    policy = meta.get("policy", POLICY)
    policy_note = (
        "Policy **exact-only**: a benchmark item counts as contaminated only when its "
        "prompt matches a training prompt exactly (after tier-0 template stripping and "
        "whitespace/case/punctuation folding). Near-duplicates -- a reformatted or "
        "reworded copy of the same problem -- are scored below and listed in "
        "`review_pairs.jsonl`, but are NOT counted as contamination. The `graded *` "
        "columns show what the stricter rule would have flagged."
        if policy == "exact-only"
        else "Policy **graded**: exact match, long verbatim run, n-gram containment or "
        "MinHash near-duplicate all count as contamination."
    )
    lines = [
        "# Train/eval contamination report",
        "",
        f"Rows scanned: {meta['rows_scanned']}",
        "",
        policy_note,
        "",
        f"n-gram orders: {meta['n_long']} (primary), {meta['n_short']} (short items). "
        f"Thresholds: {meta['thresholds']}",
        "",
        "## Per-benchmark",
        "",
        "| benchmark | items | dirty | exact | evaluated | eval dirty | graded dirty | "
        "graded suspect | eval graded dirty | max run (tok) | max 13-gram | max minhash |",
        "|---|---|---|---|---|---|---|---|---|---|---|---|",
    ]
    for row in summary:
        lines.append(
            f"| {row['benchmark']} | {row['n_items']} | {row['dirty']} | {row['exact']} | "
            f"{row['n_evaluated']} | {row['evaluated_dirty']} | {row['graded_dirty']} | "
            f"{row['graded_suspect']} | {row['evaluated_graded_dirty']} | "
            f"{row['max_run_tokens']} | {row['max_ngram13']:.3f} | {row['max_minhash']:.3f} |"
        )

    lines += ["", "## Affected trained corpora", ""]
    if affected:
        for corpus, items in sorted(affected.items()):
            lines.append(f"- `{corpus}`: {len(items)} dirty eval items")
    else:
        lines.append("- none: no `dirty` item traces to any trained corpus.")

    lines += [
        "",
        "## Next steps",
        "",
        "1. Adjudicate `review_pairs.jsonl` by hand -- these are candidates, not",
        "   verdicts. Shared boilerplate and common code idioms do produce",
        "   false positives at the `suspect` level.",
        "2. Run `impact_analysis.py` to split *measured* per-token acceptance into",
        "   flagged vs clean. Only a material gap justifies a retrain/rerun.",
        "",
    ]
    path.write_text("\n".join(lines))


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--eval-data-dir", type=Path, default=EVAL_DATA_DIR)
    parser.add_argument(
        "--benchmarks",
        default="",
        help="comma-separated file stems to restrict to (default: every *.jsonl)",
    )
    parser.add_argument(
        "--sources",
        default="",
        help="comma-separated corpus keys to scan (default: all of "
        + ",".join(DEFAULT_SOURCES)
        + ")",
    )
    parser.add_argument("--output-dir", type=Path, default=Path(__file__).resolve().parent / "out")
    parser.add_argument("--workers", type=int, default=min(32, (os.cpu_count() or 8) - 2))
    parser.add_argument(
        "--limit-rows",
        type=int,
        default=0,
        help="cap rows per chunk (smoke test); 0 = no cap",
    )
    parser.add_argument("--evidence-cap", type=int, default=3, help="evidence records per item per chunk")
    parser.add_argument(
        "--policy",
        choices=("graded", "exact-only"),
        default="exact-only",
        help=(
            "verdict rule. exact-only (default): only a normalized-exact prompt "
            "match counts as contamination; near-duplicates are scored and "
            "reported but treated as clean. graded: also flag on long verbatim "
            "runs, n-gram containment and MinHash near-duplicates."
        ),
    )
    args = parser.parse_args()

    global POLICY
    POLICY = args.policy

    benchmarks = {b.strip() for b in args.benchmarks.split(",") if b.strip()} or None
    if args.sources:
        keys = [k.strip() for k in args.sources.split(",") if k.strip()]
        missing = [k for k in keys if k not in DEFAULT_SOURCES]
        if missing:
            raise SystemExit(f"unknown source(s): {missing}. known: {list(DEFAULT_SOURCES)}")
        sources = {k: DEFAULT_SOURCES[k] for k in keys}
    else:
        sources = dict(DEFAULT_SOURCES)

    absent = [f"{k} -> {v}" for k, v in sources.items() if not os.path.exists(v)]
    if absent:
        raise SystemExit("missing corpus file(s):\n  " + "\n  ".join(absent))

    args.output_dir.mkdir(parents=True, exist_ok=True)

    print("building eval index ...", flush=True)
    items = load_eval_items(args.eval_data_dir, benchmarks)
    if not items:
        raise SystemExit(f"no eval prompts found under {args.eval_data_dir}")
    hasher = MinHasher()
    index = EvalIndex(items, hasher)
    print(
        f"  {len(items)} eval prompts | {len(index.long)} distinct {N_LONG}-grams | "
        f"{len(index.short)} distinct {N_SHORT}-grams",
        flush=True,
    )

    global _IDX
    _IDX = index  # inherited by fork; never pickled

    tasks = build_tasks(sources, args.limit_rows, args.evidence_cap)
    print(f"scanning {len(tasks)} chunks over {len(sources)} corpora with {args.workers} workers ...", flush=True)

    start = time.time()
    partials = []
    ctx = mp.get_context("fork")
    with ctx.Pool(args.workers) as pool:
        for done, part in enumerate(pool.imap_unordered(_scan_chunk, tasks), 1):
            partials.append(part)
            if done % 10 == 0 or done == len(tasks):
                print(f"  {done}/{len(tasks)} chunks ({time.time() - start:.0f}s)", flush=True)

    scores, meta = aggregate(index, partials)
    used = _evaluated_ids()
    summary = summarize(scores, used)

    scores_path = args.output_dir / "eval_item_scores.jsonl"
    with scores_path.open("w") as handle:
        for score in scores:
            slim = {k: v for k, v in score.items() if k != "evidence"}
            handle.write(json.dumps(slim) + "\n")

    review_path = args.output_dir / "review_pairs.jsonl"
    n_review = 0
    with review_path.open("w") as handle:
        for score, item in zip(scores, index.items):
            # Under exact-only the graded near-duplicates are not findings, but
            # they stay listed so the policy decision remains auditable.
            if score["verdict"] == "clean" and score["graded_verdict"] == "clean":
                continue
            span = ""
            if score["evidence"]:
                span = longest_common_span(
                    tokens(item.core), tokens(train_core(score["evidence"][0]["train_prompt"]))
                )
            handle.write(
                json.dumps(
                    {
                        "verdict": score["verdict"],
                        "graded_verdict": score["graded_verdict"],
                        # Read this first: it decides most adjudications.
                        "longest_common_span": span,
                        "benchmark": score["benchmark"],
                        "id": score["id"],
                        "was_evaluated": score["id"] in used.get(score["benchmark"], set()),
                        "longest_run_tokens": score["longest_run_tokens"],
                        "ngram13_containment": score["ngram13_containment"],
                        "minhash_jaccard": score["minhash_jaccard"],
                        "splits": score["splits"],
                        "eval_core": item.core[:3000],
                        "matches": score["evidence"],
                    }
                )
                + "\n"
            )
            n_review += 1

    report = {
        "meta": meta | {"sources": sources, "elapsed_s": round(time.time() - start, 1)},
        "summary": summary,
        "evaluated_ids": {k: sorted(v) for k, v in used.items()},
    }
    (args.output_dir / "contamination_report.json").write_text(json.dumps(report, indent=2))
    write_markdown(args.output_dir / "contamination_report.md", summary, meta, scores)

    print()
    print(f"policy: {args.policy}")
    header = (
        f"{'benchmark':<16}{'items':>7}{'dirty':>7}{'exact':>7}{'evald':>7}"
        f"{'e.dirty':>9}{'grd.dirty':>11}{'grd.susp':>10}{'e.grd.dirty':>13}"
    )
    print(header)
    print("-" * len(header))
    for row in summary:
        print(
            f"{row['benchmark']:<16}{row['n_items']:>7}{row['dirty']:>7}{row['exact']:>7}"
            f"{row['n_evaluated']:>7}{row['evaluated_dirty']:>9}{row['graded_dirty']:>11}"
            f"{row['graded_suspect']:>10}{row['evaluated_graded_dirty']:>13}"
        )
    print(f"\nwrote {scores_path}")
    print(f"wrote {review_path} ({n_review} items to adjudicate)")
    print(f"wrote {args.output_dir / 'contamination_report.md'}")


if __name__ == "__main__":
    main()
